# Generated by Django 6.0.3 on 2026-03-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='categoria',
            field=models.CharField(choices=[('trabajo', 'Trabajo'), ('videojuegos', 'Videojuegos'), ('personal', 'Tiempo libre / Personal'), ('otro', 'Otro')], default='trabajo', max_length=20),
        ),
    ]
