# Generated by Django 6.0.3 on 2026-03-09 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerario', '0002_alter_tarea_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='categoria',
            field=models.CharField(choices=[('trabajo', 'Trabajo'), ('personal', 'Personal'), ('deporte', 'Deporte'), ('ejercicio', 'Ejercicio'), ('videojuego', 'Videojuego'), ('juego', 'Juego'), ('familiar', 'Familiar'), ('salud', 'Salud'), ('musica', 'Musica'), ('otro', 'Otro')], default='trabajo', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('invitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='itinerario.tarea')),
            ],
            options={
                'ordering': ['-creado_en'],
                'unique_together': {('tarea', 'invitado')},
            },
        ),
        migrations.AddField(
            model_name='tarea',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, related_name='tareas_compartidas', through='itinerario.Invitacion', through_fields=('tarea', 'invitado'), to=settings.AUTH_USER_MODEL),
        ),
    ]
